### ISSUE TITLE
deeplink transactions with payload are not working since 5.x update 

### ISSUE THREAD

**Issue by IRGC** [tonkeeper/android#104]
**Describe the bug**
deep link transactions are not working since 5.x update 

whenever we click on link like this with `bin` payload `ton://transfer/<address>?amount=10000000&bin=<url-encoded-base64-boc>`  or `https://app.tonkeeper.com/transfer/<address>?amount=10000000&bin=<url-encoded-base64-boc>`

app says emulation failed and the transaction is not going through.

payload is valid and has been working fine till 4.12x version.

**To Reproduce**
click on any deep link with `bin` payload

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/1cad1215-30bb-47dc-ba76-d828ba25f122)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by IRGC** [comment]
@sorokin0andrey @polstianka can you please check?

**Comment by polstianka** [comment]
This is fixed in version 5.0.16 which will be in Google Play soon (dev branch)
