### ISSUE TITLE
Unable to transfer TON using w5 wallet

### ISSUE THREAD

**Issue by ben622** [tonkeeper/android#61]
Branche: dev

Received an error message from the RPC node:

 {"error":"error code: 0 message: cannot apply external message to current state : External message was not accepted\nCannot run message on account: inbound external message rejected by transaction 2A4B4A2582C60256C9F9B5EED78197E6D56A77A68A4DF33343F8A13581961AC0:\nexitcode=138, steps=9, gas_used=0\nVM Log (truncated):\n...execute SETCP 0\nexecute DICTPUSHCONST 19 (xC_,1)\nexecute DICTIGETJMPZ\nexecute implicit JMPREF\nexecute DUP\nexecute PLDU 32\nexecute PUSHINT 1936287598\nexecute EQUAL\nexecute THROWIFNOT 138\ndefault exception handler, terminating vm with exit code 138\n"}

**Comment by polstianka** [comment]
Hi, has this fixed with the latest "dev" branch updates?

**Comment by ben622** [comment]
Trying again success
