### ISSUE TITLE
 scammed on Nft voucher given by tonkeeper

### ISSUE THREAD

**Issue by laykonjibson** [tonkeeper/android#8]
I was sent an NFT voucher which was verified to be true on tonkeeper wallet , when I claimed the nft voucher as said on the wallet 92$ was removed from my account in which they said the gas fee was $0.66. I want my money back to my wallet. they are suppose to blacklist an unauthorized nft but they support it. the recipients address: UQDONoaamQWwlhH-m1AvjN6Okt4DlUi0eyMV8xJQRCjXASw0 and the website to claim the voucher is tonbounty.com

**Comment by Chris0ppp** [comment]
Hello

**Comment by TonyDEv-lab** [comment]
@laykonjibson It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
